name: CI

on:
  push:
    branches-ignore: [ main ]  # Don't run on main as npm-publish.yml handles that
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint (fail on warnings)
      run: npm run lint
      env:
        ESLINT_MAX_WARNINGS: 0
    
    - name: Build
      run: npm run build
    
    - name: Test with coverage
      run: npm run test:coverage
    
    # - name: Upload coverage reports
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     directory: ./coverage/
    #     fail_ci_if_error: false