name: Manual Publish to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: 'Dry run (no actual publish)'
        required: true
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        # This is important for the npm version command to work correctly
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
      env:
        ESLINT_MAX_WARNINGS: 0
    
    - name: Test
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Bump version
      if: ${{ !inputs.dry_run }}
      run: |
        npm version ${{ inputs.version }} -m "Bump version to %s [skip ci]"
        git push
        git push --tags
    
    - name: Publish to npm (dry run)
      if: ${{ inputs.dry_run }}
      run: npm publish --dry-run
    
    - name: Publish to npm
      if: ${{ !inputs.dry_run }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}