name: Publish to npm

on:
  # Trigger on PR merge to main
  push:
    branches: [ main ]
  # Optionally trigger on tags
  # tags:
  #   - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Needed for pushing commits and tags
      pull-requests: read  # Needed for reading PR information
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Fetch enough history for version bump determination
        fetch-depth: 50
        ref: ${{ github.ref }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
      env:
        ESLINT_MAX_WARNINGS: 0
    
    - name: Test
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Determine version bump type
      id: version-bump
      run: |
        # Enable bash debugging
        set -x
        
        # Get the merge commit message (PR title)
        PR_TITLE=$(git log -1 --pretty=%s)
        echo "PR Title: $PR_TITLE"
        
        # Get all commit messages from the PR
        echo "Analyzing recent commit messages (if available)..."
        # Try to get commit messages, but don't fail if we can't
        COMMIT_MESSAGES=""
        if git rev-parse HEAD~10 >/dev/null 2>&1; then
          COMMIT_MESSAGES=$(git log HEAD~10..HEAD --format=%s)
        else
          # If we can't get 10 commits back, try with fewer
          for i in {5..1}; do
            if git rev-parse HEAD~$i >/dev/null 2>&1; then
              COMMIT_MESSAGES=$(git log HEAD~$i..HEAD --format=%s)
              echo "Found $i commits to analyze"
              break
            fi
          done
        fi
        
        # If we still don't have any commit messages, just use the PR title
        if [ -z "$COMMIT_MESSAGES" ]; then
          echo "No commit history available, using only PR title for analysis"
          COMMIT_MESSAGES="$PR_TITLE"
        fi
        
        # Initialize bump type as patch (default)
        BUMP_TYPE="patch"
        
        # Function to check for conventional commit prefixes
        check_for_prefixes() {
          local message="$1"
          
          # Check for breaking changes (highest priority)
          if [[ "$message" == *"BREAKING CHANGE"* ]] || [[ "$message" == *"!"* ]]; then
            echo "Detected breaking change - using major version bump"
            BUMP_TYPE="major"
            return 0
          fi
          
          # Check for features (medium priority)
          if [[ "$message" == "feat"* ]] || [[ "$message" == "feat:"* ]] || [[ "$message" =~ "feat\(" ]]; then
            # Only upgrade to minor if we haven't already decided on major
            if [[ "$BUMP_TYPE" != "major" ]]; then
              echo "Detected new feature - using minor version bump"
              BUMP_TYPE="minor"
            fi
            return 0
          fi
          
          # Check for fixes (lowest priority)
          if [[ "$message" == "fix"* ]] || [[ "$message" == "fix:"* ]] || [[ "$message" =~ "fix\(" ]]; then
            # Only set to patch if we haven't decided on minor or major
            if [[ "$BUMP_TYPE" != "major" ]] && [[ "$BUMP_TYPE" != "minor" ]]; then
              echo "Detected bug fix - using patch version bump"
              BUMP_TYPE="patch"
            fi
            return 0
          fi
          
          return 1
        }
        
        # First check the PR title (highest priority)
        check_for_prefixes "$PR_TITLE"
        
        # Save the current BUMP_TYPE after checking PR title
        echo "After PR title check: BUMP_TYPE=$BUMP_TYPE"
        
        # Process commit messages one by one
        echo "Processing commit messages:"
        echo "$COMMIT_MESSAGES" > /tmp/commit_messages.txt
        while IFS= read -r message; do
          echo "Processing message: $message"
          if [[ -n "$message" ]]; then
            check_for_prefixes "$message"
            echo "After checking message: BUMP_TYPE=$BUMP_TYPE"
          fi
        done < /tmp/commit_messages.txt
        
        echo "BUMP_TYPE after processing all messages: $BUMP_TYPE"
        
        # Output the final decision
        echo "Final decision: $BUMP_TYPE version bump"
        
        # Set the output in a way that works with both older and newer GitHub Actions
        if [ -n "$GITHUB_OUTPUT" ]; then
          # New way (GitHub Actions runner >= 2.297.0)
          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
        else
          # Old way (GitHub Actions runner < 2.297.0)
          echo "::set-output name=bump_type::$BUMP_TYPE"
        fi
    
    - name: Bump version
      run: |
        echo "Bumping version: ${{ steps.version-bump.outputs.bump_type }}"
        # Debug output
        echo "Version bump type from previous step: ${{ steps.version-bump.outputs.bump_type }}"
        
        # Set up git user
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Use npm version to bump version, create commit and tag
        npm version ${{ steps.version-bump.outputs.bump_type }} -m "Bump version to %s [skip ci]"

        # Push changes back to the repository with better error handling
        echo "Pushing changes to repository..."
        # Set the remote URL with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Push changes and tags
        git push origin HEAD:main
        git push origin --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}