name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR Title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Configure which types are allowed (from conventional commits spec)
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        # Configure if a scope is required
        requireScope: false
        # Configure if the subject may be empty
        subjectPattern: ^(?!\s*$).+
        # Configure additional validation for the subject based on a regex
        subjectPatternError: |
          The subject must not be empty and must not end with a period.
        # Configure if the subject may start with uppercase
        wip: true
        # Configure if the PR is allowed to be a work in progress
        validateSingleCommit: false
        # Configure if the PR title should be validated against a single commit
        validateSingleCommitMatchesPrTitle: false
        # Configure if the PR title should match the commit message