name: Branch Validation

on:
  push:
    branches-ignore: 
      - main  # Don't run on main as npm-publish.yml handles that
    paths-ignore:
      - '**.md'  # Ignore markdown files
      - 'docs/**'  # Ignore documentation updates

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    # Only run this job for pushes that are not associated with a PR
    # This prevents duplicate builds when PRs are updated
    if: github.event_name == 'push' && github.event.pull_request == null

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint (fail on warnings)
      run: npm run lint
      env:
        ESLINT_MAX_WARNINGS: 0
    
    - name: Build
      run: npm run build
    
    - name: Test with coverage
      run: npm run test:coverage